/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTasksRouteImport } from './routes/api/tasks'
import { Route as ApiTasksIdRouteImport } from './routes/api/tasks.$id'

const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksRoute = ApiTasksRouteImport.update({
  id: '/api/tasks',
  path: '/api/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIdRoute = ApiTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTasksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/tasks': typeof TasksRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/api/tasks/$id': typeof ApiTasksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/tasks': typeof TasksRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/api/tasks/$id': typeof ApiTasksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/tasks': typeof TasksRoute
  '/api/tasks': typeof ApiTasksRouteWithChildren
  '/api/tasks/$id': typeof ApiTasksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/tasks'
    | '/api/tasks'
    | '/api/tasks/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/contact' | '/tasks' | '/api/tasks' | '/api/tasks/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/tasks'
    | '/api/tasks'
    | '/api/tasks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  TasksRoute: typeof TasksRoute
  ApiTasksRoute: typeof ApiTasksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks': {
      id: '/api/tasks'
      path: '/api/tasks'
      fullPath: '/api/tasks'
      preLoaderRoute: typeof ApiTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$id': {
      id: '/api/tasks/$id'
      path: '/$id'
      fullPath: '/api/tasks/$id'
      preLoaderRoute: typeof ApiTasksIdRouteImport
      parentRoute: typeof ApiTasksRoute
    }
  }
}

interface ApiTasksRouteChildren {
  ApiTasksIdRoute: typeof ApiTasksIdRoute
}

const ApiTasksRouteChildren: ApiTasksRouteChildren = {
  ApiTasksIdRoute: ApiTasksIdRoute,
}

const ApiTasksRouteWithChildren = ApiTasksRoute._addFileChildren(
  ApiTasksRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  TasksRoute: TasksRoute,
  ApiTasksRoute: ApiTasksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
