/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AddPerfumeRouteImport } from './routes/add-perfume'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPerfumesRouteImport } from './routes/api/perfumes'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiTasksIdRouteImport } from './routes/api/tasks.$id'
import { Route as ApiPerfumesRouteImport } from './routes/api/perfumes.'

const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPerfumeRoute = AddPerfumeRouteImport.update({
  id: '/add-perfume',
  path: '/add-perfume',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPerfumesRoute = ApiPerfumesRouteImport.update({
  id: '/api/perfumes',
  path: '/api/perfumes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTasksIdRoute = ApiTasksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTasksRoute,
} as any)
const ApiPerfumesRoute = ApiPerfumesRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApiPerfumesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-perfume': typeof AddPerfumeRoute
  '/contact': typeof ContactRoute
  '/manage': typeof ManageRoute
  '/shop': typeof ShopRoute
  '/api/contact': typeof ApiContactRoute
  '/api/perfumes': typeof ApiPerfumesRouteWithChildren
  '/api/perfumes/': typeof ApiPerfumesRoute
  '/api/tasks/$id': typeof ApiTasksIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-perfume': typeof AddPerfumeRoute
  '/contact': typeof ContactRoute
  '/manage': typeof ManageRoute
  '/shop': typeof ShopRoute
  '/api/contact': typeof ApiContactRoute
  '/api/perfumes': typeof ApiPerfumesRoute
  '/api/tasks/$id': typeof ApiTasksIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/add-perfume': typeof AddPerfumeRoute
  '/contact': typeof ContactRoute
  '/manage': typeof ManageRoute
  '/shop': typeof ShopRoute
  '/api/contact': typeof ApiContactRoute
  '/api/perfumes': typeof ApiPerfumesRouteWithChildren
  '/api/perfumes/': typeof ApiPerfumesRoute
  '/api/tasks/$id': typeof ApiTasksIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/add-perfume'
    | '/contact'
    | '/manage'
    | '/shop'
    | '/api/contact'
    | '/api/perfumes'
    | '/api/perfumes/'
    | '/api/tasks/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/add-perfume'
    | '/contact'
    | '/manage'
    | '/shop'
    | '/api/contact'
    | '/api/perfumes'
    | '/api/tasks/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/add-perfume'
    | '/contact'
    | '/manage'
    | '/shop'
    | '/api/contact'
    | '/api/perfumes'
    | '/api/perfumes/'
    | '/api/tasks/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AddPerfumeRoute: typeof AddPerfumeRoute
  ContactRoute: typeof ContactRoute
  ManageRoute: typeof ManageRoute
  ShopRoute: typeof ShopRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiPerfumesRoute: typeof ApiPerfumesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-perfume': {
      id: '/add-perfume'
      path: '/add-perfume'
      fullPath: '/add-perfume'
      preLoaderRoute: typeof AddPerfumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/perfumes': {
      id: '/api/perfumes'
      path: '/api/perfumes'
      fullPath: '/api/perfumes'
      preLoaderRoute: typeof ApiPerfumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tasks/$id': {
      id: '/api/tasks/$id'
      path: '/$id'
      fullPath: '/api/tasks/$id'
      preLoaderRoute: typeof ApiTasksIdRouteImport
      parentRoute: typeof ApiTasksRoute
    }
    '/api/perfumes/': {
      id: '/api/perfumes/'
      path: '/'
      fullPath: '/api/perfumes/'
      preLoaderRoute: typeof ApiPerfumesRouteImport
      parentRoute: typeof ApiPerfumesRoute
    }
  }
}

interface ApiPerfumesRouteChildren {
  ApiPerfumesRoute: typeof ApiPerfumesRoute
}

const ApiPerfumesRouteChildren: ApiPerfumesRouteChildren = {
  ApiPerfumesRoute: ApiPerfumesRoute,
}

const ApiPerfumesRouteWithChildren = ApiPerfumesRoute._addFileChildren(
  ApiPerfumesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AddPerfumeRoute: AddPerfumeRoute,
  ContactRoute: ContactRoute,
  ManageRoute: ManageRoute,
  ShopRoute: ShopRoute,
  ApiContactRoute: ApiContactRoute,
  ApiPerfumesRoute: ApiPerfumesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
